---
- name: deploy nginx service.
  hosts: nginx
  remote_user: root
  roles:
    - nginx

- name: deploy php-fpm service.
  hosts: php
  remote_user: root
  roles:
    - php

- name: deploy mysql service.
  hosts: mysql
  remote_user: root
  roles:
    - mysql
