# Generated by Django 2.1.12 on 2019-09-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
