# Generated by Django 2.1.12 on 2019-09-05 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_articlepost_views_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlepost',
            old_name='views_count',
            new_name='total_views',
        ),
    ]
