version: '2'
services:
    web:
        image: djangowithmysql
        depends_on:
            - mysql
        build:
            context: .
            dockerfile: Dockerfile
        environment:
           MYSQL_ROOT_PASSWORD: 123456
           MYSQL_DATABASE: blog
           HOST: mysql
        ports:
         - "8000:8000"
        working_dir: /app
        networks:
         - gtsb
        restart: always
    mysql:
        image: mysql:5.7
        volumes:
           - mysql-data:/var/lib/mysql
        environment:
           TZ: 'Asia/Shanghai'
           MYSQL_ROOT_PASSWORD: 123456
           MYSQL_DATABASE: blog
        command: ['mysqld', '--character-set-server=utf8']
        networks:
         - gtsb
networks:
    gtsb:

volumes:
    mysql-data:

